#!/usr/bin/env bash

set -euo pipefail
shopt -s extglob

ETC_AS=etc-as
PYTHON3=python3

fatal() { echo "[FATAL] $@" >&2 ; exit 1 ; }

version() { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

check_python310_install() {
    if ! [ $(version $(python3 --version)) -ge $(version "3.10.0") ] ; then
        PYTHON3=python3.10
    fi
    which $PYTHON3 &> /dev/null \
        || fatal "Must have python3.10 or newer installed. Try the \`make deps\` target that came with etc-as."
}

INSTALL_BIN="$(cd "$(dirname "$0")" && pwd)"
INSTALL_LIB="$(dirname "$INSTALL_BIN")/lib/$ETC_AS"

run_etcas() {
    $PYTHON3 "$INSTALL_LIB/etc-as.py" "$@"
}

if [[ $# -eq 0 ]] ; then
    set -- "--help"
fi

if [[ "${1:-}" == 'version' ]] || [[ "${1:-}" == '--version' ]] ; then
    echo "$0"
    cat  "$INSTALL_LIB"/version
    exit 0
fi

check_python310_install
run_etcas "$@"
